version: "3.1"
nlu:
- intent: return_policy+ask_warranty
  examples: |
    - đổi trả và bảo hành
    - bảo hành và đổi trả
    - Bao hanh va doi tra
    - bảo hành, đổi trả như nào
- intent: thank+bye
  examples: |
    - Cam on nhe. Bye
    - ok. Tam biet
    - Thank. chao tam biet
    - giỏi quá. bye bye nha
    - thank. chào tạm biệt
    - Cảm ơn nhé. Bye
    - Gioi qua. bye bye nha
- intent: bye
  examples: |
    - tam biet em nhe
    - tam biet em
    - chào tạm biệt em
    - tam biet
    - bye nha
    - tạm biệt
    - chào tạm biệt
    - tạm biệt em
    - tạm biệt em nhé
    - chao tam biet
- intent: select_brand
  examples: |
    - Tôi muốn xem đồng hồ [Casio](brand)
    - [Rolex](brand)
    - [Casio](brand) đẹp
    - [Casio](brand)
    - Tôi chọn [GShock](brand)
    - Đồng hồ [Casio](brand) đi
    - Tôi chọn [Tissot](brand)
    - Chọn [Casio](brand) nè
    - [Omega](brand)
    - [Citizen](brand)
    - Tôi muốn mua [Seiko](brand)
- intent: thank
  examples: |
    - cảm ơn em
    - thanks
    - cảm ơn
    - thank you
    - ok
    - gioi
    - hay
    - tuyệt
    - cảm ơn em nhiều nhé
    - cám ơn
    - chuẩn
    - cam on em
    - tuyet
    - chuan
    - siêu
- intent: buy_watch
  examples: |
    - Đồng hồ nào đẹp
    - Mình cần mua đồng hồ
    - Toi muon mua dong ho dep
    - Hãy giới thiệu đồng hồ
    - Co dong ho nao khong?
    - Bạn có mẫu đồng hồ nào không?
    - Tôi muốn tìm một chiếc đồng hồ
    - Minh can mua dong ho
    - Ban co mau dong ho nao khong?
    - Mua dong ho
    - Toi muon mua dong ho
    - Hay gioi thieu dong ho
    - Toi muon tim mot chiec dong ho
    - Mua đồng hồ
    - Tôi muốn mua đồng hồ
    - Tôi muốn mua đồng hồ đẹp
- intent: track_order
  examples: |
    - Đơn hàng của tôi đến đâu rồi?
    - Cho tôi biết thông tin về đơn hàng
    - Don hang cua toi den dau roi?
    - Tôi có thể biết tình trạng đơn hàng không?
    - Kiểm tra trạng thái đơn hàng của tôi
    - Kiểm tra đơn hàng
    - Don hang cua toi da duoc giao chua?
    - Tôi muốn theo dõi đơn hàng
    - Xem đơn hàng của tôi đang ở đâu
    - Đơn hàng của tôi đã được giao chưa?
    - Toi muon kiem tra tinh trang don hang
    - Tôi muốn kiểm tra tình trạng đơn hàng
    - Toi co the biet tinh trang don hang khong?
    - Toi muon theo doi don hang
    - Kiem tra trang thai don hang cua toi
    - Theo dõi đơn hàng của tôi
- intent: ask_warranty
  examples: |
    - Chính sách bảo hành cho đồng hồ là gì?
    - Dong ho co duoc bao hanh khong?
    - Đồng hồ được bảo hành như thế nào?
    - Dong ho duoc bao hanh nhu the nao?
    - Bao hanh dong ho
    - Điều kiện để bảo hành đồng hồ là gì?
    - Đồng hồ có được bảo hành không?
    - Neu dong ho bi hong thi bao hanh o dau?
    - Bảo hành đồng hồ ở đâu
    - Bao hanh dong ho trong bao lau?
    - Bao hanh dong ho o dau
    - Bảo hành đồng hồ
    - Che do bao hanh dong ho ra sao?
    - Bảo hành đồng hồ trong bao lâu?
    - Toi muon biet thong tin ve bao hanh dong ho
    - Nếu đồng hồ bị hỏng thì bảo hành ở đâu?
- intent: greet
  examples: |
    - ban oi
    - chao ban
    - chào buổi sáng
    - xin chào
    - bạn ơi
    - chau oi
    - chào
    - xin chao
    - chao
    - có ai ở đây không?
    - hey
    - hello
    - hi
    - co ai giup minh khong
    - mình có vài câu hỏi
    - anh ơi
    - co ai o day khong
    - minh co vai cau hoi
    - chi oi
    - cháu ơi
    - chị ơi
- intent: ask_operating_time
  examples: |
    - Giờ mở cửa của cửa hàng là bao nhiêu?
    - Cua hang lam viec tu may gio den may gio?
    - Ban mo cua luc may gio?
    - Bạn có thể cho tôi biết giờ mở cửa của cửa hàng được không?
    - Shop lam viec den may gio?
    - Cửa hàng làm việc từ mấy giờ đến mấy giờ?
    - Shop làm việc đến mấy giờ?
    - Cửa hàng mở lúc mấy giờ?
    - Cửa hàng đóng cửa vào lúc mấy giờ?
    - Gio mo cua cua cua hang la bao nhieu?
    - May gio cua hang dong cua?
    - Khi nào cửa hàng đóng cửa?
    - Cửa hàng mở cửa vào lúc nào?
    - Cửa hàng làm việc từ mấy giờ đến mấy giờ vậy?
    - Thoi gian hoat dong cua cua hang
    - May gio cua hang bat dau mo?
    - Thời gian hoạt động của cửa hàng
    - Cua hang dong cua vao luc may gio?
    - Mấy giờ cửa hàng bắt đầu mở?
    - Cua hang mo luc may gio?
    - Khi nao cua hang dong cua?
    - Bạn mở cửa lúc mấy giờ?
- intent: purchase_process
  examples: |
    - Ban co the huong dan toi dat hang khong?
    - Cách thức đặt hàng như thế nào?
    - Quy trình mua hàng bao gồm những bước nào?
    - Tôi cần hướng dẫn về việc đặt hàng
    - Toi can giup do de dat hang
    - Toi co the dat mua truc tuyen khong?
    - Cach thuc dat hang nhu the nao?
    - Mua hàng ở đây có dễ không?
    - Tôi có thể đặt mua trực tuyến không?
    - Lam sao de dat hang tren trang web?
    - Can lam gi de dat mua mot mon hang?
    - Cach mua hang tren trang nhu the nao?
    - Có thể mua hàng qua website không?
    - Quy trinh de mua mot san pham la gi?
    - Hướng dẫn tôi cách đặt hàng với bạn
    - Dat hang online nhu the nao?
    - Toi can huong dan ve viec dat hang
    - Co the mua hang qua website khong?
    - Huong dan toi cach dat hang voi ban
    - Làm sao để đặt hàng trên trang web?
    - Quy trinh mua hang bao gom nhung buoc nao?
    - Bạn có thể hướng dẫn tôi đặt hàng không?
    - Tôi muốn biết về quy trình mua hàng
- intent: return_policy
  examples: |
    - Hang co the doi duoc khong neu khong hai long?
    - Tôi có được đổi trả nếu hàng bị lỗi không?
    - Lam the nao de toi doi tra san pham?
    - Đổi trả sản phẩm thì phải làm sao?
    - Chính sách đổi trả của bạn ra sao?
    - Dieu kien de doi tra hang la gi?
    - San pham loi co the tra lai khong?
    - Cua hang co nhan hang tra lai khong?
    - Cửa hàng có nhận hàng trả lại không?
    - Chính sách đổi trả có khó không?
    - Điều kiện để đổi trả hàng là gì?
    - Bạn có thể giải thích chính sách đổi trả không?
    - Toi co the tra hang trong bao lau?
    - Toi muon biet chinh sach doi tra
    - Bao lau thi toi co the doi tra san pham?
    - Chinh sach doi tra cua shop nhu the nao?
    - Toi co duoc doi tra neu hang bi loi khong?
    - Sản phẩm lỗi có thể trả lại không?
    - Chinh sach doi tra cua ban ra sao?
    - Tôi có thể trả hàng trong bao lâu?
    - Ban co the giai thich chinh sach doi tra khong?
    - Neu khong thich, toi co the tra hang khong?
    - Bao lâu thì tôi có thể đổi trả sản phẩm?
    - Doi tra san pham thi phai lam sao?
- intent: ask_address
  examples: |
    - Địa chỉ của shop ở đâu
    - Xin địa chỉ cửa hàng
    - Cho toi biet cua hang nam o dau duoc khong
    - Dia chi
    - Cửa hàng nằm vị trí nào
    - Dia chi cua shop o dau
    - Cua hang nam vi tri nao
    - Toi muon di den tan noi tan cua hang
    - Cho mình xin địa chỉ của shop
    - Tôi muốn đi đến tận nơi tận cửa hàng
    - Cua hang cua ban nam o dau
    - Cho tôi biết cửa hàng nằm ở đâu được không
    - Xin dia chi cua hang
    - Tôi có thể ghé cửa hàng không
    - Vị trí cửa hàng
    - Co cua hang nao gan day khong
    - Vi tri cua hang
    - Cho toi xin vi tri cua ban nhe
    - Ghe shop nha
    - Địa chỉ
    - Shop nằm ở đâu
    - Toi co the ghe cua hang khong
    - Có cửa hàng nào gần đây không
    - Cho tôi xin vị trí của bạn nhé
- intent: specify_gender
  examples: |
    - Giup toi voi, toi can mua dong ho [Nam](gender) tot
    - Có đồng hồ [Unisex](gender) nào không?
    - [unisex](gender) dep
    - Đồng hồ [Nữ](gender)
    - Bạn có mẫu [Nam](gender) nào đẹp không?
    - Dong ho [Nam](gender)
    - Dong ho [Nu](gender)
    - [nam](gender) cho dep
    - Mua đồng hồ [Nam](gender)
    - [Nam](gender)
    - Mua dong ho [Nam](gender)
    - Toi muon mot dong ho [Nu](gender)
    - Giúp tôi với, tôi cần mua đồng hồ [Nam](gender) tốt
    - Đồng hồ [Nam](gender)
    - [nam](gender) cho đẹp
    - Tôi muốn một đồng hồ [Nữ](gender)
    - Toi muon mua dong ho [Nu](gender)
    - [unisex](gender) đẹp
    - Tôi cần đồng hồ cho [Nam](gender)
    - Tôi muốn mua đồng hồ [Nam](gender)
    - Toi dang tim mot chiec dong ho [Nu](gender)
    - Mua đồng hồ [Nữ](gender)
    - Toi can dong ho cho [Nam](gender)
    - [Unisex](gender)
    - Co dong ho [Unisex](gender) nao khong?
    - Giup toi voi, toi can mua dong ho [Nu](gender) tot
    - Toi muon mua dong ho [Nam](gender)
    - [Nữ](gender)
    - [Nu](gender)
    - [nữ](gender) cho đẹp
    - Giúp tôi với, tôi cần mua đồng hồ [Nữ](gender) tốt
- intent: ask_for_watch_by_rating
  examples: |
    - Hiển thị những đồng hồ được [4](rating) sao
    - Toi muon xem dong ho [ba](rating) sao
    - Đồng hồ được đánh giá [4](rating) sao
    - Đồng hồ [bốn](rating) sao
    - Nhung dong ho [3](rating) sao
    - Nhung dong ho [ba](rating) sao
    - Hien thi nhung dong ho duoc [4](rating) sao
    - [hai](rating) sao
    - Dong ho [5](rating) sao
    - Cac dong ho [bon](rating) sao
    - Đồng hồ [5](rating) sao
    - Những đồng hồ [ba](rating) sao
    - Các đồng hồ [bốn](rating) sao
    - Đồng hồ [5](rating) sao đánh giá
    - Dong ho nao co danh gia [nam](rating) sao
    - Những đồng hồ [3](rating) sao
    - Toi muon xem dong ho [5](rating) sao
    - Dong ho [bon](rating) sao
    - Đồng hồ được đánh giá [bốn](rating) sao
    - Dong ho nao [nam](rating) sao
    - Dong ho [5](rating) sao danh gia
    - [4](rating) sao đồng hồ
    - Tôi muốn xem đồng hồ [5](rating) sao
    - Cac dong ho [4](rating) sao
    - Dong ho duoc danh gia [4](rating) sao
    - Hiển thị những đồng hồ được [hai](rating) sao
    - Dong ho duoc danh gia [bon](rating) sao
    - Tôi muốn xem đồng hồ [ba](rating) sao
    - [mot](rating) sao
    - [5](rating) sao
    - Đồng hồ nào [năm](rating) sao
    - Đồng hồ nào có đánh giá [năm](rating) sao
    - [3](rating) sao
    - [một](rating) sao
    - [4](rating) sao
- intent: ask_name
  examples: |
    - tên của anh là gì
    - cho mình hỏi tên nhé
    - tên em
    - vui lòng cho mình biết tên nhé
    - cho em xin tên của anh ạ
    - de tien xung ho thi ten ban la gi
    - bạn tên là gì
    - minh muon tien xung ho hon, cho minh biet ten nhe
    - ban ten la gi
    - tên của bạn là gì
    - ten gi
    - anh tên gì
    - cho minh hoi ten nhe
    - vui long cho minh biet ten nhe
    - cho em xin tên của chị ạ
    - xin phep hoi ten cua ban
    - em tên là gì thế
    - chúng ta nên biết tên nhau nhỉ?
    - ten cua chi la gi
    - mình muốn biết tên bạn
    - anh ten gi
    - ten cua anh la gi
    - em ten la gi the
    - cho em xin ten cua anh a
    - minh muon biet ten ban
    - ten em
    - bạn có vui lòng cho mình biết tên được không
    - mình muốn tiện xưng hô hơn, cho mình biết tên nhé
    - tên gì
    - tên bạn
    - được biết tên bạn thì tốt nhỉ
    - chị tên gì
    - xin phép hỏi tên của bạn
    - ten cua ban la gi
    - bạn tên gì
    - tên bạn trong tiếng việt là gì
    - chi ten gi
    - ban co vui long cho minh biet ten duoc khong
    - cho em xin ten cua chi a
    - tên em là gì
- intent: out_of_scope
  examples: |
    - Bạn biết ai phát minh ra điện thoại không
    - Chó hay mèo thông minh hơn
    - Tai sao bau troi lai co mau xanh
    - Ban biet ai phat minh ra dien thoai khong
    - Lam the nao de tro thanh nguoi giau co
    - Ban biet choi bong da khong
    - Bạn nghĩ gì về trí tuệ nhân tạo
    - Bạn có thích xem phim không
    - Doi qua
    - Ban da tung di den Viet Nam chua
    - Có cách nào học tiếng Anh nhanh không
    - Solo tay doi hong
    - Tai sao 1 ngay co 24 gio
    - Tôi nên đi du lịch ở đâu vào mùa hè này
    - Solo tay đôi hông
    - Ai la ca si noi tieng nhat hien nay
    - Thoi tiet hom nay the nao
    - Ban thich an mon gi
    - Đường đến nhà ga gần nhất ở đâu
    - Ai là ca sĩ nổi tiếng nhất hiện nay
    - Toi nen di du lich o dau vao mua he nay
    - Ban nghi gi ve tri tue nhan tao
    - Cho hay meo thong minh hon
    - Chan qua
    - nước biển có màu gì
    - Bạn thích ăn món gì
    - Thời tiết hôm nay thế nào
    - hom nay co tran da bong nao
    - hôm nay có trận đá bóng nào
    - Đói quá
    - nuoc bien co mau gi
    - Ban co thich xem phim khong
    - Ve so hom nay ra con gi
    - Lam the nao de nau mot bat pho ngon
    - Ai la tong thong My
    - Hôm nay có trận bóng đá nào không
    - Tại sao bầu trời lại có màu xanh
    - Chán quá
    - Bạn có biết chơi cờ vua không
    - Duong den nha ga gan nhat o dau
- intent: give_name
  examples: |
    - [Co](cust_sex) [Xuan Mai](cust_name)
    - [Ông](cust_sex) tên [Phúc](cust_name)
    - [Tôi](cust_sex) là [Minh](cust_name)
    - [Bà](cust_sex) là [Liên](cust_name)
    - [Xuân Vũ](cust_name)
    - [Toi](cust_sex) la [Huy](cust_name) day
    - [Be](cust_sex) la [Mai](cust_name)
    - [Toi](cust_sex) la [Minh](cust_name)
    - [Con](cust_sex) ten [Ha](cust_name)
    - ten [Bao](cust_name)
    - [Co](cust_sex) [Mai](cust_name)
    - [Anh](cust_sex) [Bảo](cust_name)
    - [Chú](cust_sex) là [Toàn](cust_name)
    - [Minh](cust_sex) ten la [Khang](cust_name)
    - [Chị](cust_sex) là [Ngọc](cust_name)
    - [Vũ](cust_name)
    - [Chi](cust_sex) la [Ngoc](cust_name)
    - [Tôi](cust_sex) là [Huy](cust_name) đây
    - [Gọi tôi](cust_sex) là [Thành](cust_name)
    - [Anh](cust_sex) [Bảo Phạm](cust_name)
    - [Tên tôi](cust_sex) là [Minh](cust_name)
    - tên [Tuấn KKhang](cust_name)
    - [Em](cust_sex) ten la [Linh](cust_name)
    - [Goi toi](cust_sex) la [Thanh](cust_name)
    - [Chu](cust_sex) [Tuan](cust_name)
    - [Em](cust_sex) tên là [Linh](cust_name)
    - ten [Tuan Khang](cust_name)
    - [Chu](cust_sex) [Gia Tuan](cust_name)
    - [Mình](cust_sex) tên là [Khang](cust_name)
    - [Anh](cust_sex) tên [Đức](cust_name)
    - [Cháu](cust_sex) tên là [Long](cust_name)
    - [Chi](cust_sex) [Hang Nga](cust_name)
    - [Anh](cust_sex) là [Hải](cust_name)
    - [Ten toi](cust_sex) la [Minh](cust_name)
    - [Chu](cust_sex) la [Toan](cust_name)
    - [Anh](cust_sex) [Bảo](cust_name) đây
    - [Chị](cust_sex) [Hằng Nga](cust_name)
    - [Cô](cust_sex) [Xuân Mai](cust_name)
    - [Co](cust_sex) ten la [Lan](cust_name)
    - [Con](cust_sex) tên [Hà](cust_name)
    - [Cô](cust_sex) [Mai](cust_name)
    - [Xuan Vu](cust_name)
    - [Ong](cust_sex) ten [Phuc](cust_name)
    - [Bé](cust_sex) là [Mai](cust_name)
    - [Chi](cust_sex) [Hang](cust_name)
    - [Chú](cust_sex) [Tuấn](cust_name)
    - [Chị](cust_sex) [Hằng](cust_name)
    - [Tên của mình](cust_sex) là [Tuấn](cust_name)
- intent: ask_func_list
  examples: |
    - minh to mo ve nhung viec ban lam duoc
    - biết làm gì
    - mình tò mò về những việc bạn làm được
    - ban co the lam gi
    - ke cho minh biet nhung viec ban co the lam duoc nhe
    - có làm được trò gì
    - ban biet lam gi
    - ban huu dung nhu the nao
    - ban giup duoc gi nao
    - em giúp được gì
    - bạn biết được những lĩnh vực gì
    - bạn giỏi nhất làm gì
    - em biết làm gì
    - em làm được gì
    - noi cho minh ve nhung viec ban giup duoc minh
    - bạn có thể làm được mấy chức năng
    - mày biết làm gì
    - ban biet duoc nhung linh vuc gi
    - ban co ich trong nhung viec gi
    - chẳng biết bạn làm được gì
    - bạn có ích trong những việc gì
    - bạn tệ nhất trong việc gì
    - ban co the lam duoc may chuc nang
    - bạn giúp được mình gì nào
    - việc gì bạn làm được
    - ban co the lam duoc nhung gi
    - bạn giúp được gì nào
    - nói cho mình về những việc bạn giúp được mình
    - bạn hữu dụng như thế nào
    - co lam duoc gi
    - bạn có thể làm được những gì
    - bạn có thể làm gì
    - lam duoc gi
    - co lam duoc tro gi
    - viec gi ban lam duoc
    - em biet lam gi
    - em lam duoc gi
    - ban co tu van giup minh duoc khong
    - chang biet ban lam duoc gi
    - kể xem bạn làm được gì
    - bạn giỏi hỗ trợ nhất trong lĩnh vực gì
    - biet lam gi
    - lĩnh vực gì bạn giỏi nhất
    - chuc nang cua ban la gi
    - ban gioi nhat lam gi
    - may biet lam gi
    - linh vuc gi ban gioi nhat
    - bạn biết làm gì
